version: "3.6"

services:
  sse:
    image: percona/percona-server:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sse
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_PASSWORD: root
    volumes:
      - "/var/lib/mysql"
#    network_mode: host
    restart: always
    container_name: sse
  vehicle-charging:
    build: .
    ports:
      - 8080:8080
    volumes:
      - "/tmp:/tmp"
      - "/tmp/inbox:/tmp/inbox"
      - "/tmp/outbox:/tmp/outbox"
    #    network_mode: host
    container_name: vehicle-charging
    depends_on:
      - sse
