version: "3.6"

services:
  baggage-handler:
    image: builders/baggage-handler:latest
    ports:
      - 8080:8080
    volumes:
      - "/tmp/inbox:/tmp/inbox"
      - "/tmp/outbox:/tmp/outbox"
    networks:
      - bh_network
    container_name: baggage-handler

  payload-receiver1:
    image: builders/gateway
    ports:
      - 8081:8081
    volumes:
      - "$PWD/src/test/resources/payload-receiver/mappings:/mappings"
    networks:
      - bh_network
    command: --port 8081
    container_name: payload-receiver1

  payload-receiver2:
    image: builders/gateway
    ports:
      - 8082:8082
    volumes:
      - "$PWD/src/test/resources/payload-receiver/mappings:/mappings"
    networks:
      - bh_network
    command: --port 8082
    container_name: payload-receiver2

  job-deliverer1:
    image: builders/gateway
    ports:
      - 8083:8083
    volumes:
      - "$PWD/src/test/resources/job-deliverer/mappings:/mappings"
      - "$PWD/src/test/resources/job-deliverer/__files:/__files"
    networks:
      - bh_network
    command: --port 8083
    container_name: job-deliverer1

  job-deliverer2:
    image: builders/gateway
    ports:
      - 8084:8084
    volumes:
      - "$PWD/src/test/resources/job-deliverer/mappings:/mappings"
      - "$PWD/src/test/resources/job-deliverer/__files:/__files"
    networks:
      - bh_network
    command: --port 8084
    container_name: job-deliverer2

  state-store:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - bh_network
    restart: always
    container_name: state-store

networks:
  bh_network:
