version: "3.6"

services:
  payload-receiver1:
    image: builders/gateway:latest
    ports:
      - 8081:8081
    volumes:
      - "$PWD/src/test/resources/payload-receiver/mappings-local:/mappings"
    network_mode: host
    command: --port 8081
    container_name: payload-receiver1

  payload-receiver2:
    image: builders/gateway:latest
    ports:
      - 8082:8082
    volumes:
      - "$PWD/src/test/resources/payload-receiver/mappings-local:/mappings"
    network_mode: host
    command: --port 8082
    container_name: payload-receiver2

  job-deliverer1:
    image: builders/gateway:latest
    ports:
      - 8083:8083
    volumes:
      - "$PWD/src/test/resources/job-deliverer/mappings-local:/mappings"
      - "$PWD/src/test/resources/job-deliverer/__files:/__files"
    network_mode: host
    command: --port 8083
    container_name: job-deliverer1

  job-deliverer2:
    image: builders/gateway:latest
    ports:
      - 8084:8084
    volumes:
      - "$PWD/src/test/resources/job-deliverer/mappings-local:/mappings"
      - "$PWD/src/test/resources/job-deliverer/__files:/__files"
    network_mode: host
    command: --port 8084
    container_name: job-deliverer2

  state-store:
    image: mongo:latest
    ports:
      - 27017:27017
    network_mode: host
    restart: always
    container_name: state-store